services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: postgres-server
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=docprocessor
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  # Backend Python service (FastAPI + Worker)
  backend:
    build: ./backend
    ports:
      - "8080:8000"
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres-server:5432/docprocessor
    restart: unless-stopped
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network

  # Frontend Next.js service
  frontend:
    build: ./frontend
    ports:
      - "3010:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

# Volumes
volumes:
  postgres_data:

# Networks
networks:
  app-network:
    driver: bridge
